### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR for gzip'd files

### ISSUE THREAD

**Issue by benbalter** [wp-document-revisions/wp-document-revisions#254]
This issue is intended to track https://wordpress.org/support/topic/failed-to-load-pdf-document-12/ and https://wordpress.org/support/topic/lastest-update-furbars-links/.

My theory is that with the introduction of `gzip` compression, the `content-length` header is incorrect since [we're returning the length of the non-compressed file in the header](https://github.com/wp-document-revisions/wp-document-revisions/blob/master/includes/class-wp-document-revisions.php#L1178-L1179), but the true content length is less. Based on https://stackoverflow.com/questions/58215104/whats-the-neterr-http2-protocol-error-about, I suspect this can lead to an error when using HTTP2 + gzip.

That leaves us with two options:

1. Remove the `content-length` header entirely. https://stackoverflow.com/questions/15991173/is-the-content-length-header-required-for-a-http-1-0-response suggests it's not required, and may work in most cases, but may break in some cases like Android.
2. Return the length of the gzip'd file (for example, as described in https://stackoverflow.com/questions/815961/how-to-determine-the-content-length-of-a-gzipped-file). This adds complexity in terms of another `ob_buffer` layer, but may result in greater compatibility.

@NeilWJames thoughts? Does that explanation potentially make sense for you? I'm happy to tackle the first fix, if we wanted to go that route, but given your recent `ob_buffer` work, I may ask if you would be willing to tackle the second fix, if we wanted to go that route instead.

**Comment by NeilWJames** [comment]
@benbalter,
I have been spending a lot of the day trying some experiments. What is certainly true is that with proxy servers and intermediate servers what the original client asks for is not necessarily what arrives at the server.

Your point 1. is probably the issue for HTTP/2 - namely that Content-Length is not required - but if it is there then it needs to be correct. The protocol error is the defined error for this circumstance. So we need to remove the length header.

With HTTP/1.0 or HTTP/1.1 the original file length is generally longer than the compressed file, so there is no problem with the gzip download and a longer length. I believe that we should leave the length header there for these versions.

If there are browsers that do not support gzip and others that do, then with caching, delivering a gzip file to one that doesn't support it can cause issues. Thus we should ensure an VARY: Accept-Encoding header that will ensure no issue.

If the files are compressed "externally" to the application using DEFLATE then it modifies the etag entry from "xxx" to "xxx-gzip".
This has the effect that caching will be disabled. I have done a fix for this.

I have tried a number of routes to get the length of the compressed file, but invoking the gzip option and looking at the length doesn't work - I always get the original file length, not the zipped one. I'll try an alternative one shortly. This will be to encode it before writing to the buffer. If this works, then the length will be valid for HTTP/2.

Looking at the "error messages" from Chromium saying that Cache-Control should be used instread of Expire, so I would propose using this header. The existing 3 years expiry time seems a little long. I would propose 3 months.

I propose to make these changes in my version, probably tomorrow and will make a pull request when OK.

Regards,
Neil

**Comment by allinappli** [comment]
Trying to download a PDF leads to this error (which I think is related to this issue): `Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR`

**Comment by benbalter** [comment]
Thanks to @NeilWJames's wonderful work in #255, this issue should be fixed in [3.3.1](https://github.com/wp-document-revisions/wp-document-revisions/releases/tag/3.3.1). If you experienced an`ERR_HTTP2_PROTOCOL_ERROR` in 3.3.0, please try 3.3.1, and comment below if it is still unresolved.
