### ISSUE TITLE
Provide a read-only REST Interface for documents

### ISSUE THREAD

**Issue by NeilWJames** [wp-document-revisions/wp-document-revisions#259]
A recent issue (#258) raised the issue of having the post-type to be set as "show_in_rest" as true.

This would enable the links function in the block editor to display document URLs.
(And, of course, document linkages to be extracted with no log-on.)

The underlying functionality within the plug-in hides the name of the file containing the actual document by changing the name of the download file to be an md5-encoded version of the name and load time.

So before supporting the REST interface we need to ensure that it will not expose this encoded filename.
 
It should also be noted that, on loading the file, if it is a PDF file, then WordPress functionality will create thumbnail images of its first page – with their names are based on the loaded file name. If they are to be used like a featured image, their name needs to be changed so as not to expose the file name if used at all – let alone in the REST interface.

When the parameter is set to true, then the standard Posts controller will create a series of end-points with the rest base name of “document” (i.e. singular) and unlike the equivalent posts or pages. When invoking this functionality, it should invoke the base_name to be the slug name as set on the site, i.e. “documents” by default.

The default REST interface provides GET, POST, PUT, PATCH and DELETE methods, but given the defined structure of the post type and the limited updates that can be made, only the GET interface should be available.

Additional validation checks should be made to ensure that

1. Revisions should only be provided to those with “read_document_revisions” capability.
2. Read capability should be checked using the current_user_can( $post_type->cap->read ) test which will be either “read” or “read_documents” depending in filter “document_read_uses_read” (see issue #256).
3. If GET is used with context “edit” then return an error.

Before returning data to the user, it should be cleaned as follows:
**Document or Revision**: If user does not have “read_document_revisions” capability, remove links to “version-history” – count of revisions; and “predecessor-version” – previous revision.
**Attachment**: For document attachments, replace the contents of “slug”, “title” and possibly “description” and “meta_details” when the generated image names have not been altered as these can contain the encoded name,

As the REST functionality is not required, it is proposed that it is enabled by use of a filter “document_show_in_rest” overriding false to true, rather than it being available implicitly.

**Comment by NeilWJames** [comment]
@benbalter,
I would propose to be creating a new Pull request shortly. 
I will add a number of different functions in it - and they are rather co-mingled.
I will raise these 6 separate issues so that the different elements can be understood separately and they can be better understood as tointent and implementation.

**Comment by benbalter** [comment]
@NeilWJames Thank you. Reading through the issues, I'm really excited to see the PRs and review. Thank you, as always, for your thoughtful contributions.

**Comment by NeilWJames** [comment]
Addressed by #265
