### ISSUE TITLE
Block categories deprecation

### ISSUE THREAD

**Issue by webelaine** [wp-document-revisions/wp-document-revisions#280]
### Describe the bug

When WP Document Revisions is active and the debug log is enabled locally, entering the Block Editor for any post type adds the following deprecation notice:

[23-Feb-2022 16:47:51 UTC] PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in /Users/{username}/Sites/{sitename}/wp-includes/functions.php on line 5691

This appears to be coming from `/includes/class-wp-document-revisions-front-end.php` and can be solved by changing the hook on line 463 from `block_categories` to `block_categories_all`.

**Comment by benbalter** [comment]
Thanks @webelaine for opening an issue. Would you be willing to submit a pull request to make that change? I assume the APIs remain the same between the methods, or would other changes be required beyond updating the method names?

**Comment by webelaine** [comment]
Looks like this was actually fixed in https://github.com/wp-document-revisions/wp-document-revisions/commit/9934d0dabae6377d317dbb01c49afb8e6064b893 but that fix hasn't made it to WP.org. Anything I can do to help get that fix released publicly?

**Comment by benbalter** [comment]
Ahh, good catch. I can work on getting a new release cut and onto wp.org then! :rocket:

**Comment by webelaine** [comment]
Thanks, @benbalter ! The release fixed the bug.
