### ISSUE TITLE
Permalink Options without "/" ending

### ISSUE THREAD

**Issue by appliedtactics** [wp-document-revisions/wp-document-revisions#312]
In the app, all links to docs end with a "/".  For example, "filename.pdf/"

A client of mine did a number of links without the "/" at the end causing a 404.

Is there an option to have the link work with and without "/" at the end?

Thank you

**Comment by NeilWJames** [comment]
I have checked and all the rewrite lines end with /?$, that is, they expect to match either with or without the final terminating "/".
Would it be possible to give one or more examples where it works with the "/" but gives a 404 without it please. (Don't need/want the site name, just the part that comes after it. Also the slug used for the documents please.
Thanks,
Neil James

**Comment by NeilWJames** [comment]
Closed as no further information supplied.

Neil James
