### ISSUE TITLE
Typo: wp_content vs wp-content

### ISSUE THREAD

**Issue by cvladan** [wp-document-revisions/wp-document-revisions#328]
It is not `wp_content` but `wp-content`.

When you do copy-paste and copy with this mistake, it takes you 20 minutes to figure out why the folder is missing.

<img width="1083" alt="image" src="https://github.com/wp-document-revisions/wp-document-revisions/assets/1913156/cd38a7f5-5f5f-429f-a186-0be84860a4b1">

**Comment by NeilWJames** [comment]
Fixed with commit [d63c63e] 
Merge branch 'main' of https://github.com/NeilWJames/wp-document-revisions
