### ISSUE TITLE
Are the recent updates enough to warrant a release?

### ISSUE THREAD

**Issue by EarthlingDavey** [wp-document-revisions/wp-document-revisions#344]
Hi, first up, thanks for this project. I appreciate the work of the maintainer and contributors :)

Would it be possible for someone to cut a release and publish to wpackagist?

**Comment by benbalter** [comment]
Thanks for the reminder @EarthlingDavey! Published [v3.6.0](https://github.com/wp-document-revisions/wp-document-revisions/releases/tag/v3.6.0).
